[package]
name = "cl"
version = "0.1.0"
authors = ["Julien Castelain <julien.castelain@liferay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.25.1"
